# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(help_text='IDC详细地址', max_length=256, verbose_name='机房地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.EmailField(default='null', help_text='邮件地址', max_length=254, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='letter',
            field=models.CharField(help_text='机房字母简称', max_length=5, verbose_name='IDC简称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(help_text='机房名称', max_length=32, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(help_text='联系电话', max_length=15, verbose_name='联系人'),
        ),
    ]
